[package]
name = "advent_of_code_2020"
version = "0.1.0"
authors = ["Ben-Lichtman"]
edition = "2018"

[dependencies]
regex = "1.4.2"
parse-display = "0.4.0"
itertools = "0.9.0"

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day2"
path = "src/day2.rs"
